

services:
  graphql-apollo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
